## 1. Tensor Flow Library :

In [ ]:
# 1) Tensor Flow Library :
#           For high performance numerical computation
#           Used across many scientific domains
#           Data in tensorflow are represented as tensors, which are multidimensional Arrays
# Features:
#           Used in deep learning models and neural networks
#           Better than Torch and thiano due to better visualizations
#           In neural machine translation, it reduces error by 50-60%
#           Parallel computing to execute complex models aka Pipelining
#           Seamless performance
#
# Applications:
#           Speech-Image recognition
#           Text based applications
#           Time Series
#           Video Detection

## 2. NumPy Library

In [3]:
# 2) NumPy Library :
#           General Purpose Array-Processing package
#           NumPy is the fundamental package for numerical computation with python, it contains a powerful
#               N-Dimensional Array object
#           Provides fast precompiled functions for numerical routines
#           Array oriented computing for better performance
#           Supports object-oriented approach
#           Compact and faster Computations
# Features:
#           Provides fast precompiled functions for numerical routines
#           Array oriented  computing for Better efficiency
#           Supports Object-oriented approach
#           Compact and faster computations with vectorization

# Applications:
#           Used extensively in data analysis
#           Powerful in creation of n-dimensional array
#           Useful in machine learning models
#           Forms the base of the other libraries such as SciPy,Scikit-Learn
#           Machine learning models have the base of NumPy
#           Can act as a replacement for Matlab whn used with SciPy,Matpotlib
#

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a.shape)

(3,)


In [12]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
b=np.array(12)

In [10]:
b

array(12)

# 3. SCIPY

### It Stands For Scientific Python

### 1. It has a collection of mathematical algorithm and scientific function built on numpy extension pf python
### 2. It has High level commands and classes for manipulation and visualization of data
### 3. It includes function for computing, integrals, numerical solving etc.

In [2]:
# 3) SciPy Library :
#           Used extensively in data analysis science for high level computations
# Features:
#           A large collection of algorithms and scientific functions built on NumPy
#           Has high level commands and classes for data manipulations and visualizations
#           Multi dimensional image processing with SciPy.ndimage
#           Includes functions for computing integrals numerically, solving differential equations,optimization, etc
#
# Applications:
#           Multi dimensional image operations
#           Solving differential equations
#           Optimization Algorithms
#           Linear Algebra

In [15]:
from scipy import constants

In [17]:
print (constants.c) #speed of light
print (constants.h) #plank's constant
print (constants.N_A) #Avogadra's number

299792458.0
6.62607015e-34
6.02214076e+23


## 4. Pandas

### PANDA stands for Python Data Analysis Library

#### It is used for Data analysis & cleaning

##### It provides fast , flexible and  expressive data structures designed to work with structured data easily and intuitively

##### Eloquent Syntax & rich Functionality and high level Data Structures

In [5]:
# 4) Pandas (MOST WIDELY USED):
#           PANDAS Stand for python data analysis
#           Used for data analysis and cleaning
# Features:
#           Eloquent syntax and Rich functionalities
#           'Apply()' enables you to run a function across a series of data
#           High Level Abstraction
#           Contains high-level data structures and manipulation tools
# Application:
#           General Data wrangling
#           Useful in ETL jobs in data storage and transformation
#           Used in varieties of Academic and commercial domains including statistics etc
#           Useful in time series specific functionality

In [20]:
import pandas as pd

In [22]:
#Creating data frames

#Creating our own data and putting it in to a data frames

df= pd.DataFrame(np.random.randn(6,4),index=list(range(6)),columns=list("ABCD"))
df

A         B         C         D
0 -0.515712 -0.926848  0.208694  0.128763
1  0.744916 -0.815245 -1.387668  1.655053
2 -1.805658  0.215964 -0.309207  1.109305
3  1.279719 -0.569346 -0.100155 -0.422900
4 -0.645657  2.677277  0.794225 -1.816657
5 -1.167258 -0.971496  0.554437  2.452769

In [25]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.351608 -0.064949 -0.039946  0.517722
std    1.162457  1.412854  0.775040  1.540992
min   -1.805658 -0.971496 -1.387668 -1.816657
25%   -1.036858 -0.898948 -0.256944 -0.284984
50%   -0.580685 -0.692296  0.054270  0.619034
75%    0.429759  0.019637  0.468001  1.518616
max    1.279719  2.677277  0.794225  2.452769

# 5. MATPLOTLIB

### It is a plotting libraray for Python 
### it is used for Data Visualization

In [6]:
# 5) MatPlotLib:
#           Plotting library for python
#           Used for data visualization
#           It provides an object-oriented API for embedding plots into applications
# Features:
#           As usable as matlab with an advantage of free and open source
#           Supports dozens of backend and output types
#           Pandas can itself be used a wrappers around MATPLOTLIB's API
#           Small memory consumption and very good runtime behaviour
# Applications:
#           Correlation of analysis of variables
#           Visualize 95% confidence intervals of the models
#           Outlier Detection
#           Visualizing the distributions to gain instant insights